enum RenderCmd : Int
{
  case END
  case CLEAR_COLOR
  case PUSH_OBJECT_TRANSFORM
  case POP_OBJECT_TRANSFORM
  case PUSH_VIEW_TRANSFORM
  case POP_VIEW_TRANSFORM
  case PUSH_PROJECTION_TRANSFORM
  case POP_PROJECTION_TRANSFORM
}
